### ISSUE TITLE
Séance 1

### ISSUE THREAD

**Issue by MaxleDrut** [MaxleDrut/TP-GL#1]
- [x] Intro
- [x] Répartition
- [x] Functional + non functional reqs
- [x] Analysis of secu
- [x] Test plan for tests
- [x] User manual

**Comment by 0nyr** [comment]
- [ ]  Test de validation : test fonctionnels de fonctions globales (cas d'utilisation, toute une 
fonction se déroule de manière correcte, test de haut niveau).
- [ ] Test de bas niveau, test unitaires des fonctions
- [ ] Use case diagram
- [ ] Class diagram
- [ ] Sequence diagram
